### ISSUE TITLE
Change introduced in release 5.2 breaks sandbox connection

### ISSUE THREAD

**Issue by StephenBadger** [sezzle/sezzle-magento2#11]
The update to the file Model/System/Config/Container/SezzleIdentity.php which changes the sandboxGatewayUrl from https://sandbox.gateway.sezzle.com to https://staging.gateway.sezzle.com causes my authentication requests to have a 401 response. It would appear that the API keys generated from https://sandbox.dashboard.sezzle.com/merchant/settings/apikeys are not valid for the staging.gateway.sezzle.com domain.

As a result I have to force composer to install version 5.1.1, which does work.

**Comment by arijit-sezzle** [comment]
I am aware of that and the fix will be released in some time.

**Comment by arijit-sezzle** [comment]
Released!
