### ISSUE TITLE
Magento 2.4.2-P1 Sezzle Error The requested qty is not available

### ISSUE THREAD

**Issue by harendraprajapati** [sezzle/sezzle-magento2#12]
Team,

When Configurable Child Last Item into Cart It is throwing error The requested qty is not available.

Senario, 
Add Product Configurable with Simple Product into cart Which Simple Product (Child) have qty "1" (Last Item).
Process For Checkout Payment with Sezzle it is throwing Error "The requested qty is not available" 

<img width="1299" alt="Screen Shot 2021-08-27 at 4 36 21 PM" src="https://user-images.githubusercontent.com/36778877/131192307-408bb2e0-3f3e-442e-a60a-8659a57d4015.png">

<img width="1325" alt="Screen Shot 2021-08-27 at 4 56 27 PM" src="https://user-images.githubusercontent.com/36778877/131192889-132aafb1-7174-487e-b8e2-af3820b839b9.png">

For Example there is Configurable Child Product 2 qty & add to Cart 2 qty. It is also given Same Error.

https://test.com/checkout/?deliveryType=ship#payment

![image](https://user-images.githubusercontent.com/36778877/131191344-e8a2d76c-9639-46ec-9e91-2486f1925656.png)

![image](https://user-images.githubusercontent.com/36778877/131191387-347537ed-f5a5-4491-b697-f970f039727d.png)

Sezzle Trying Both Version 5.5.1 & 5.5.2 But Still Same issue.
![image](https://user-images.githubusercontent.com/36778877/131190881-0ab2c53c-62d3-4344-90a6-5092700154d3.png)

Other Magento Default Payment Method working Fine with successful Order Placed ( Like PayPal, Amazon Pay, Check / Money Order etc)

Please Help me with that..

**Comment by arijit-sezzle** [comment]
Thanks for reporting this. I will look into this and post here on further updates.

**Comment by arijit-sezzle** [comment]
This is WIP.

**Comment by arijit-sezzle** [comment]
This is fixed in v5.5.3.
