### ISSUE TITLE
Public repo has higher version than private repo causing composer errors in 2.4.3

### ISSUE THREAD

**Issue by ntoombs19** [sezzle/sezzle-magento2#13]
In Magento 2.4.3, a new composer plugin was added: `magento/composer-dependency-version-audit-plugin`

This plugin only does one thing and that is to check if there are any versions of a package on a public repo (`https://repo.packagist.org/`) that have a version number that is higher than that package on the private repo (`https://repo.magento.com/`).

Running `composer update sezzle/sezzlepay` results in the following error message being displayed:

```
 [Exception]                                                                                                                                   
  Higher matching version 5.5.3 of sezzle/sezzlepay was found in public repository packagist.org                                                
                               than 5.5.2 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,   
                               please investigate and update package requirement to match the version from the private repository         
```

The this is a major problem for any Magento store on 2.4.3 currently running sezzle as it prevents us from running any composer commands while this package is installed via composer. The immediate fix would be to publish the 5.5.3 upgrade to the magento marketplace and to avoid publishing the public releases before the private releases.

**Comment by ntoombs19** [comment]
https://magento.com/blog/best-practices/adobe-releases-new-composer-plugin-magento-243-release

**Comment by arijit-sezzle** [comment]
Thanks for reporting the issue. We will be looking into this.

**Comment by arijit-sezzle** [comment]
Released in the marketplace.
