### ISSUE TITLE
Class 'Zend\Log\Writer\Stream' not found

### ISSUE THREAD

**Issue by petresdaniel** [sezzle/sezzle-magento2#14]
### Preconditions (*)
Magento 2.4.3

### Steps to reproduce (*)
- payment/sezzlepay/log_tracker config has to be enabled
- save the payment admin config for Sezzle payment

### Expected result (*)
Admin config is saved

### Actual result (*)
An error is thrown. `Class 'Zend\Log\Writer\Stream' not found`

In Magento 2.4.3 'laminas-log' has been removed. So the laminas-zendframework-bridge doesn't work anymore for the Log.

This is the magento commit that deleted the composer dependency:
https://github.com/magento/magento2/commit/f0840b19d820d866ed9c5680e97aac0210237068#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

This is the problematic line in sezzle-magento2:
https://github.com/sezzle/sezzle-magento2/blob/master/Helper/Data.php#L18

**Comment by arijit-sezzle** [comment]
Fix has been released at - https://github.com/sezzle/sezzle-magento2/releases/tag/v5.5.5
