### ISSUE TITLE
Product Detail Page (PDP) Widget is not working

### ISSUE THREAD

**Issue by xeontcs** [sezzle/sezzle-magento2#15]
Magento ver. 2.4.2
Sezzle - 5.5.5

Product Detail Page (PDP) Widget is not working.

I debugged JS. It seems they ignore path and use hardcoded in widget-renderer.js one.

`<div id="sezzle-widget"/>` after the price element in the PDP is present.

**Comment by arijit-sezzle** [comment]
Yea, the one in `widget-renderer.js` is our default configuration. If that does not load the Sezzle widget in PDP, please reach out to merchantsupport@sezzle.com.
