### ISSUE TITLE
syntax error on line 66  Sezzle\Sezzlepay\Model\Order\SaveHandler

### ISSUE THREAD

**Issue by eoiny1** [sezzle/sezzle-magento2#16]
https://github.com/sezzle/sezzle-magento2/blob/2508dd12cad1ed1e6717f609eab2c0b13c1d7ad7/Model/Order/SaveHandler.php#L66

should be  ` private  $productMetadata;`

**Comment by arijit-sezzle** [comment]
Which PHP version are you using?

**Comment by eoiny1** [comment]
v7.3.33
Let me update to a later version and see if that is the issue
