### ISSUE TITLE
Undefined array key sezzlepay

### ISSUE THREAD

**Issue by gustahthorres** [sezzle/sezzle-magento2#19]
Hello everyone.

I am having problems with Sezzle, because it is giving me an error when I give it "save configuration" in the store configuration, when I review the error, it indicates this message:

{"0":"Warning: Undefined array key \"sezzlepay\" in \/var\/www\/vhosts\/dev9.sbmedicaldeveloper.com\/httpdocs\/vendor\/sezzle\/sezzlepay\/Plugin\/Config\/Controller\/Adminhtml\/System\/Config\/SavePlugin.php on line 113","1":"#1 Sezzle\\Sezzlepay\\Plugin\\Config\\Controller\\Adminhtml\\System\\Config\\SavePlugin->aroundExecute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#2 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#3 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Config\/Controller\/Adminhtml\/System\/Config\/Save\/Interceptor.php:23]\n#4 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#5 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#6 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/module-config\/Controller\/Adminhtml\/System\/AbstractConfig.php:69]\n#7 Magento\\Config\\Controller\\Adminhtml\\System\\AbstractConfig->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#8 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#9 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:145]\n#10 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#11 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#12 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Config\/Controller\/Adminhtml\/System\/Config\/Save\/Interceptor.php:32]\n#13 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#14 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#15 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#16 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#17 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#18 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#21 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#22 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/admin_baiq83FNQt2d26W2K6Vuw5AQ6UVqua\/admin\/system_config\/save\/key\/c8424a6fca5604a6f8bac98cabeb55424e271fce658a2890457c4584c5e07240\/section\/themecore\/","script_name":"\/pub\/index.php","report_id":"6a808a4b9d2b1113b9c6d01d87c134e8744d2fe859318c16c1b134aec2bd319f"}

I am running magento 2.4.5-p1 and php 8.1

**Comment by arijit-sezzle** [comment]
@gustahthorres A new version 7.0.7 has been that contains the fix.
