### ISSUE TITLE
Sezzle payment option at checkout not working

### ISSUE THREAD

**Issue by psol7** [sezzle/sezzle-magento2#2]
Sezzle payment is not working, the option is showing at checkout but when you click place order nothing is happening. no error in log.
Magento ver. 2.2.3
Amasty One Step Checkout ( I tried with default checkout but to no avail)

Sizzle url: https://gateway.sezzle.com
I entered public and private key as per dashboard.
Did I missed something? What gives?

**Comment by arijit-sezzle** [comment]
@psol7 did you found any error logs in console? Or if debug.log is there, can you check if anything is over there?

**Comment by rishimukherjee** [comment]
@psol7 What is your email id? Let's connect in email over Sezzle support.

**Comment by psol7** [comment]
Safari console:

Failed to load resource: the server responded with a status of 503 (Service Unavailable)

nothing in var/log/bug.log

**Comment by psol7** [comment]
email ID?

I am the developer for newvape.com <http://newvape.com/>

NewVape, LLC.
ID
ef41c6ad-db2f-461f-a715-edc56d246515

**Comment by rishimukherjee** [comment]
Yeah! We can resolve this issue via email from sezzle support. So I need your email.

**Comment by psol7** [comment]
I added me as user and started a chat

**Comment by arijit-sezzle** [comment]
This is solved now.
