### ISSUE TITLE
Undefined index: pdp_widget_enabled or Undefined index: sezzle_enabled - Sezzle 7.0.7

### ISSUE THREAD

**Issue by fuzzyjared** [sezzle/sezzle-magento2#20]
Magento 2.4.3-p3
Sezzle: 7.0.7

When saving payment methods on anything other than the Scope: Default config I am receiving the error undefined index: pdp_widget_enabled or Undefined index: sezzle_enabled.

Output of one of Payment method configuration changes made when within a site level scope.

{"0":"Notice: Undefined index: pdp_widget_enabled in \/vendor\/sezzle\/sezzlepay\/Plugin\/Config\/Controller\/Adminhtml\/System\/Config\/SavePlugin.php on line 257","1":"#1 Sezzle\\Sezzlepay\\Plugin\\Config\\Controller\\Adminhtml\\System\\Config\\SavePlugin->getNewConfig() called at [vendor\/sezzle\/sezzlepay\/Plugin\/Config\/Controller\/Adminhtml\/System\/Config\/SavePlugin.php:122]\n#2 Sezzle\\Sezzlepay\\Plugin\\Config\\Controller\\Adminhtml\\System\\Config\\SavePlugin->aroundExecute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#3 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#4 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Config\/Controller\/Adminhtml\/System\/Config\/Save\/Interceptor.php:23]\n#5 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#6 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#7 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/module-config\/Controller\/Adminhtml\/System\/AbstractConfig.php:69]\n#8 Magento\\Config\\Controller\\Adminhtml\\System\\AbstractConfig->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#9 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#10 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#11 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#12 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#13 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Config\/Controller\/Adminhtml\/System\/Config\/Save\/Interceptor.php:32]\n#14 Magento\\Config\\Controller\\Adminhtml\\System\\Config\\Save\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#15 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#16 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#17 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#18 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#19 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#20 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#21 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#22 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:23]\n#23 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#24 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/a0725885fc_admin\/admin\/system_config\/save\/key\/4ab8aa3235981acca390c525584bb8ddfe0c5881b172020869313045db5ebad5\/section\/payment\/website\/2\/","script_name":"\/

**Comment by arijit-sezzle** [comment]
fixed in 7.0.8.
