### ISSUE TITLE
getMerchantUUID return null

### ISSUE THREAD

**Issue by zexperto** [sezzle/sezzle-magento2#23]
Hello support,
we noticed that you removed the merchant id from the configuration but you are still checking it in this function 
getMerchantUUID : in this class Sezzle\Sezzlepay\Gateway\Config\Config
later the payment method will be always disabled because you are checking the merchant id here
Observer/PaymentMethodAvailabilityObserver.php

**Comment by arijit-sezzle** [comment]
Hi,

Merchant ID is no longer an input thing, instead, we save it in the background. So, there won't be any issue regarding this.

Thanks

**Comment by zexperto** [comment]
when I do not use it the payment methods are disabled, when I added it again I could see the payment method, I suggest checking this when it is a guest customer in Magento

**Comment by rossdl** [comment]
Can you help us understand your suggestion more?  e.g. How is our merchant UUID related to a guest customer? Or, why are you choosing not to use it (assuming "it" is the merchant UUID)? 

Ideally, the merchant UUID is never `null`. If a merchant installs our extension and successfully saves our configuration, then a valid merchant UUID will be saved.  If it is `null`, then likely the configuration was never saved and Sezzle should not be displayed as it will not function properly.

Thank you.
