### ISSUE TITLE
Invalid XML (failing XSD validation) for `sales_order_view.xml` file

### ISSUE THREAD

**Issue by lbajsarowicz** [sezzle/sezzle-magento2#26]
The `sales_order_view` file is missing `<body>` root node, as a result it reports XSD validation failure.

https://github.com/sezzle/sezzle-magento2/blob/c7825f3bf438eccbf4a084bf823f07d22b10e789/view/frontend/layout/sales_order_view.xml#L11-L13

**Comment by arijit-sezzle** [comment]
We will take look. Thanks.

**Comment by lbajsarowicz** [comment]
The repository maintainers did not submit the update.

Fixed in https://github.com/sezzle/sezzle-magento2/commit/5a186aa8e6bf89d4958c3bf85605bbe247fd32cc
