### ISSUE TITLE
Unhandled Warning: Undefined array key "quote"

### ISSUE THREAD

**Issue by lbajsarowicz** [sezzle/sezzle-magento2#32]
In the last 7 days, we have noticed that 131 of our Customers encountered Exception during the checkout process, being unable to place an order because of Sezzle issue. 

![image](https://github.com/user-attachments/assets/b13b0a8c-9820-4927-9f56-d31dfe70dd7b)

![image](https://github.com/user-attachments/assets/62a831de-4bb2-4cac-a5c8-4f2edab5342d)

The issue occurs in `\Sezzle\Sezzlepay\Gateway\Validator\AvailabilityValidator::validate`, as the following lines refer to `quote` that is not available:

https://github.com/sezzle/sezzle-magento2/blob/b5b46a89d61bfba0f0e6865aec96fbf357efd94e/Gateway/Validator/AvailabilityValidator.php#L46-L49

**This is critical issue** and should be fixed as soon as possible.

**Comment by jtmu21** [comment]
@lbajsarowicz THANKS for reporting the issue, we are looking into it. Which version of the plugin are you on? e.g. 7.0.19 or .18 etc.

**Comment by lbajsarowicz** [comment]
7.0.18

**Comment by lbajsarowicz** [comment]
@jtmu21 Any updates?

**Comment by jtmu21** [comment]
Hi @lbajsarowicz Apology for the delay. The fix is currently under testing and we will keep you posted.

**Comment by lbajsarowicz** [comment]
@jtmu21 Do we have any updates here? I see that 7.0.19 also does not provide the fix.

**Comment by jtmu21** [comment]
@lbajsarowicz Apology again for delay, we have been performing some additional tests again the fix and our goal is to release it later this week. Given that you are the first and only one who reported this issue so far, we would like to be extra cautious about the fix and ensure it would not be a breaking change for our merchants. Thanks for your understanding and pls stay tuned.

**Comment by lbajsarowicz** [comment]
@jtmu21 based on the number of the "uncaught" issues I am reporting since we installed your extension, it does not indicate the problem does not occur in other Clients' stores. It does mean that Clients don't know about the issues or they don't know where / how to report the bug reports.

**Comment by jtmu21** [comment]
@lbajsarowicz FYI, we have released the fix and currently waiting for Magento team to review and approve. Pls stay tuned and THANKS for you patience!

**Comment by arijit-sezzle** [comment]
A new version 7.0.20 has been released that fixes this issue.
