### ISSUE TITLE
Magento 2.3.1 compatibility 

### ISSUE THREAD

**Issue by sebi-p** [sezzle/sezzle-magento2#4]
The Sezzle M2 extension is not compatible with Magento version 2.3.1 because it requires "magento/framework": ">=100.0.4 <=102".

Do you have a release schedule for adjusting the requirements and compatibility?

**Comment by arijit-sezzle** [comment]
We are going to fix it in our next release which will be available soon.

**Comment by arijit-sezzle** [comment]
This is solved now.
