### ISSUE TITLE
Issue With Merchant Id Validation 

### ISSUE THREAD

**Issue by ylgendev** [sezzle/sezzle-magento2#5]
We have our merchant id a mix of Characters and Numbers .
Ex: tp0g0ovtiu1m2ci1 (this is not a real merchant_id )

When we configured the extension in our Magento 2.3.2-p2 site . 
And set this two options to Yes : 
**Add Widget Script in Pdp**
**Add Widget Script in Cart Page**
https://cl.ly/3a4ad49ab33c

Going into product page and cart page , we faced a js issue : 
uncaught SyntaxError: Unexpected token b in JSON at position 91
https://cl.ly/3cbd743bdfca

This issue was related to the merchant_id being a mixed chars and int , while in templates : 
https://github.com/sezzle/sezzle-magento2/blob/master/view/frontend/templates/product.phtml
https://github.com/sezzle/sezzle-magento2/blob/master/view/frontend/templates/cart.phtml
It want to be an integer.

I added "" on the merchant id value , and it removed the js issue .

**Comment by arijit-de** [comment]
@ylgendev This is resolved. Please upgrade to version 3.1.7.

**Comment by arijit-sezzle** [comment]
@ylgendev This is resolved. Please upgrade to version 3.1.7.
