### ISSUE TITLE
Guest checkout with tokenization - Error - Customer is charged but order is not saved in M2

### ISSUE THREAD

**Issue by drew7721** [sezzle/sezzle-magento2#7]
Sezzle version : 5.0.0
Magento version : 2.3.3-p1

STR: 

1. enable customer tokenization
2. in-context checkout disabled
3. Place an order as a guest
4. You will be redirected to Sezzle
5. Note the Option to _"Approve `STORE` to process payments from your Sezzle account for future transactions. You may revoke this authorization at any time in your Sezzle Dashboard."_ is showing on the "You're approved" page.
6. Check the option to _"Approve .... future transactions...."_
7. Complete the order.
8. It will fail to save the data and cause an error.

This is due to the fact that there is not check if the customer is logged in when creating preparing the customer payload.
See : https://github.com/sezzle/sezzle-magento2/blob/8fdb62594bfcee2d94cc6a64e2e73720a467d339/Model/Api/PayloadBuilder.php#L132-L134

This will fail when the response is returned on this line : 
https://github.com/sezzle/sezzle-magento2/blob/8fdb62594bfcee2d94cc6a64e2e73720a467d339/Model/Tokenize.php#L252
because there is no customer `id` hence no customer.

I will submit a PR for this in a minute.

**Comment by drew7721** [comment]
Note that when this happens, Sezzle will charge the customer as a completed order but M2 will not save the order. This is quite a major bug so please check the PR https://github.com/sezzle/sezzle-magento2/pull/8 and release ASAP.

Thank you.

**Comment by arijit-sezzle** [comment]
We already have a check-in for the guest customer and so I don't think it will raise an error while saving order in Magento.
https://github.com/sezzle/sezzle-magento2/blob/8fdb62594bfcee2d94cc6a64e2e73720a467d339/Model/Tokenize.php#L135

**Comment by drew7721** [comment]
Ok, I've rested this and the issue might have been due to the authorization limit on the sandbox. The fact that the option to approve future transactions was present seemed to be the cause for this as it worked when that option was not selected and it would always fail when the option was selected.
