### ISSUE TITLE
Auth Expires after 30 min.

### ISSUE THREAD

**Issue by drew7721** [sezzle/sezzle-magento2#9]
Sezzle : 5.0.0
Magento: 2.3.3-p1

### STR
Configuration : 
- Payment action : Authorize **only**

1. Place an order and wait, don't capture it right away. 
2. After 30 min the order will be cancelled because it was not captured.

---
### Issue

It might be that the merchant can not process or ship the order right away. There could be a delay up to even a few days if there is no stock. Hence this should be configurable in the admin or the min increased to at least two weeks.

I believe the API does offer this option to set the expiration time under https://docs.sezzle.com/#create-a-session under `Order object` and `checkout_expiration`. This should be added when building the order payload based on an admin config or a minimum of 7 days if not more.

### Solution
Add the `checkout_expiration` to the payload returned by this method.

https://github.com/sezzle/sezzle-magento2/blob/8fdb62594bfcee2d94cc6a64e2e73720a467d339/Model/Api/PayloadBuilder.php#L88-L106

**Comment by arijit-sezzle** [comment]
I think you have already got a reply on this from our team and also, that it cannot be configurable from the Sezzle Configuration in Magento admin at this point in time, I am closing this issue.
